.gitignore
Makefile
README.md

we use gox to release.. 
removed windows version

release process update

---

cli/command/user/create.go

Also adds support for passing password as arg to user create

Prevent passwords being empty or < 8 chars

---

cli/command/login/cmd.go
cli/command/logout/cmd.go
pkg/validation/validation.go
pkg/validation/validation_test.go

This should fix the erroneous user input processing that was causing knownHost matching to fail

Fix login/out host processing

---

cli/command/cli.go
cli/debug/debug.go
cli/flags/common.go
cmd/storageos/storageos.go

Also disable the --log-level param as there's no way to use it.

Toggle log output with debug flag

---

cli/command/login/cmd.go
cli/command/logout/cmd.go
cli/command/volume/unmount_linux.go

Pipeline http://ci.storageos.net/job/product-build/job/bugfix%252FDEV-1806-login-command-doesnt-prompt/

Login command doesn't prompt for creds with env vars set

---

cli/command/cli.go
cli/command/cluster/cmd.go
cli/command/commands/commands.go
cli/command/namespace/cmd.go
cli/command/node/cmd.go
cli/command/policy/cmd.go
cli/command/pool/cmd.go
cli/command/rule/cmd.go
cli/command/user/cmd.go
cli/command/volume/cmd.go

Adds shortcut aliases to many commands (volume -> vol etc).
Adds hidden `install-bash-completion` command to generate and install the bash completion.

Command shortcuts and bash completion

---

pkg/mount/volume.go
pkg/mount/volume_test.go

Adds retry if mkfs fails and adds a timeout context.

Mkfs retries

---

cli/command/volume/inspect.go

Pipeline: http://ci.storageos.net/view/Pipelines/job/product-build/job/feature%252FDEV-1801-cli-storageos-volume-inspect-should/

Inspect all volumes as default behaviour

---

cli/command/volume/remove.go

Controlplane changes: http://code.storageos.net/projects/STORAGEOS/repos/control/pull-requests/459/overview
Pipeline: http://ci.storageos.net/view/Pipelines/job/product-build/job/bugfix%252FDEV-1800-nice-rm-output-on-not-exist/

add volume reference to not found error

---

cli/command/commands/commands.go

I think this should be a visible option?  It might remind me to install it!
Tested on MacOS.  Will write some docs.

Un-hide bash completion, and work on MacOS

---

cli/command/system/version.go
version/client.go

Found some repetition while going through the code.

version: use GetStorageOSVersion function

---

cli/command/volume/remove.go

storageos volume rm --all will request that all volumes are deleted, if
a volume is mounted it will be passed over.
storageos volume rm --all -f will delete all volumes (including those
that are mounted)
Addresses #76

Add --all flag to volume rm

---

circle.yml

Upgrades to CircleCI 2 format and fixes broken binary uploads for new releases

Fix binary uploads

---

README.md

Update README for 0.9.5

---

cli/command/namespace/create.go
cli/command/namespace/update.go
cli/command/node/update.go
cli/command/pool/create.go
cli/command/rule/create.go
cli/command/rule/update.go
cli/command/volume/create.go
cli/command/volume/update.go
cli/opts/opts.go
pkg/validation/validation.go
pkg/validation/validation_test.go

Pipeline: http://ci.storageos.net/view/Pipelines/job/product-build/job/feature%252FDEV-1884-validate-labels/

add deprecation notices when users use old label values

---

cli/command/formatter/log_stream_test.go

formatter: add test for marshalEntry

---

cli/command/websocket.go
cli/command/websocket_test.go

websocket: add test for WebsocketURLs()

---

cli/command/node/update.go
cli/command/node/update_test.go

Panic was due to assignment to uninitialized label map.

[dev-1991] fix panic on node label update

---

pkg/mount/fs_types.go

re-enable lazy init

---

cli/command/node/inspect.go

This change modifies "node" package's `runInspect` to fetch all the node
details when no argument is passed. This is similar to volume inspect
code.

[dev-1925] node: fetch all the nodes when no arg passed to inspect

---

circle.yml

should fix releases with -rc1 suffix

fix tag filter

---

cli/command/logs/follow.go
cli/command/logs/follow_test.go

Show log messages of target nodes only.

logs: --follow accept target node

---

cli/command/volume/mount_linux.go

This changes how we determine if we are on a storageos node. Using the
hostname, the client checks if there exists any registered node with the
current hostname. If not, mounting fails with appropriate error.
Once we obtain a node object, we use the node.DeviceDir to check if
StorageOS device dir exists in that node. The same is used in
retryableMount.

DEV-2063 - mount: use node's DeviceDir, not the default path

---

cli/command/formatter/namespace.go
cli/command/formatter/node.go
cli/command/formatter/pool.go
cli/command/formatter/rule.go
cli/command/formatter/util.go
cli/command/formatter/util_test.go
cli/command/formatter/volume.go

Sorts labels as suggested in #110

Sort labels before writing

---

cli/command/volume/remove.go

Adds `--namespace` flag in `volume rm` subcommand. This affects `--all`
flag, which when combined with `--namespace` would remove all the
volumes only from the specified namespace. If no namespace is provided,
it fallsback to check in the default namespace.

DEV-2085: volume rm: Add namespace flag

---

cmd/storageos/storageos.go

Remove beta warning

---

cli/command/formatter/policy.go
cli/command/formatter/policy_test.go
cli/command/policy/list.go

This would help with `$ storageos policy rm $(storageos policy ls -q)`.

DEV-2557: Add quiet option to policy list

---

cli/command/logout/cmd.go

Fix [DEV-2528](http://jira.storageos.net/browse/DEV-2528).

HOST should be a required parameter for logout

---

Gopkg.lock
cli/command/cli.go
cli/command/commands/commands.go
cli/command/licence/cmd.go
cli/command/licence/create.go
cli/command/licence/inspect.go
cli/command/licence/remove.go
cli/command/policy/create.go
cli/command/user/update.go
vendor/github.com/storageos/go-api/licence.go
vendor/github.com/storageos/go-api/policy.go
vendor/github.com/storageos/go-api/types/licence.go
vendor/github.com/storageos/go-api/user.go

https://github.com/storageos/go-api/pull/51
https://github.com/storageos/go-api/pull/52
These two PR have to be merged first.

DEV-2598: support licence command

---

Gopkg.lock
Gopkg.toml
cli/command/user/create.go
vendor/github.com/storageos/go-api/types/user.go

Just for getting a green pipeline. I will change the branch back to master once the other PR is merged (https://github.com/storageos/go-api/pull/56)

DEV-2445: change JSON format of user groups from comma separated string to string array

---

Gopkg.lock
cli/command/user/create.go
vendor/github.com/storageos/go-api/types/user.go

Reverts storageos/go-cli#155
Getting unexplained integration test fails

Revert "DEV-2445: change JSON format of user groups from comma separated string to string array"

---

Gopkg.lock
Gopkg.toml
vendor/github.com/storageos/go-api/types/user.go

reverting PR in go-api: https://github.com/storageos/go-api/pull/59

update go-api to master to revert incompatible changes for slice groups

---

cli/command/commands/commands.go

Add alias for americanised spelling

Add license alias

---

README.md

Prepping for release - will cut once this is merged

Version bump to 1.2.1

---

README.md

Bump to 1.2.2
