cli/command/commands/commands.go, cli/command/system/cmd.go, cli/command/system/events.go
The `events` command should be removed while it remains in this state.
Additionally, as it was the only available command under `system` that
category is removed from the help for now.
=> DEV-1139: The `system events` option hangs

cli/command/user/update.go, glide.lock, vendor/github.com/storageos/go-api/types/user.go, vendor/golang.org/x/crypto/ssh/terminal/util_bsd.go, vendor/golang.org/x/crypto/ssh/terminal/util_linux.go
In some edge-cases extra "," separators were seen in group fields.
This change fixes this behaviour.
=> Fix bad groups formatting and update deps

cli/command/cluster/create.go, cli/command/volume/mount_linux.go, cli/command/volume/unmount_linux.go
Fixes:
```
ERRO[0000]  failed to mount volume                       err="mkdir /mnt: permission denied" mountpoint=/mnt volume_id=8c2a1ba7-f094-6a9b-11ba-8216e1f420f6
```
Now:
```
$ storageos volume mount default/test02 /mnt
volume mount requires root permission - try prefixing command with `sudo`
$ sudo STORAGEOS_USERNAME=storageos STORAGEOS_PASSWORD=XXXXX storageos volume mount default/test02 /mnt
volume test02 mounted: /mnt
$ storageos volume unmount default/test02
volume unmount must be run as root user - try prefixing command with `sudo`
$ sudo STORAGEOS_USERNAME=storageos STORAGEOS_PASSWORD=XXXXX storageos volume unmount default/test02
volume test02 unmounted: /mnt
```
=> Validate root for mounts

cli/command/cluster/create.go, cli/opts/cluster.go, cli/opts/cluster_test.go
Validates cluster size and removes prefix from cluster create output (none of the other create commands label the output)
=> Cluster validation

cli/command/cluster/create.go, cli/command/rule/create.go, cli/command/volume/create.go
Don't make users specify "--namespace default" when creating volumes or rules, just use the default namespace if not specified.
So,
`storageos volume create -d default vol1` becomes:
`storageos volume create vol1`
@oicheryl are you ok with this behaviour?
=> Default namespace

README.md
Should refer to the `storageos_darwin_amd64` binary and not `storageos_linux_amd64`
=> update install instructions for OSX

cli/command/user/create.go
Currently the (possibly empty) `--password` field fails validation if password is provided interactively.
This change fixes this feature
=> Fixes issue with interactive password input not validating

cli/command/cli.go, cli/command/login/cmd.go, cli/command/logout/cmd.go
Adds extra behaviour to the CLI to use default host on login when no host was provided.
=> Use default host on login by default

pkg/mount/volume.go
mkfs takes longer, but it's safer
=> disable lazy init

cli/command/system/version.go
There will be a global change made to the API regarding dialer timeouts.
However the version command probably requires an even shorter timeout.
Fixes #55 when paired with https://github.com/storageos/go-api/pull/29
=> Reducing version timeout

Makefile
This change amends make's `release` target to generate file hashes of all
the generated binaries. This would result in publishing binaries with their
hashes for data integrity verification.
=> makefile: release file hashes

cli/command/cluster/health.go, types/types.go
Add sorting by node name to cluster health so it works better when using `watch storageos cluster health` to monitor status
=> sort cluster health node list by name

cli/command/cluster/inspect.go, discovery/client.go
Command now returns an error id the given CID is not a UUID
Adds error handling for 404 errors (e.g. when a UUID id given, but not a
known token)
Adds error handling for unknown status responses from the discovery
service
=> Only use valid cluster IDs

Makefile, README.md
Saves having to copy the binary into your path when developing.
The `touch version/client.go` just makes sure you're rebuilding it.
=> Add Makefile target to build and install into GOPATH

cli/command/formatter/volume.go, cli/command/rule/create.go, cli/config/config.go
Fixes the issue with the replica count being n/0 on `storageos volume ls`.
(Tested with node/0.10 in UE 3-node config)
Our e2e tests should have caught this.
I doubt that this output will change with much regularity so I think we should make them stricter about letting this kind of thing through. Even if the test is a little fragile against CLI changes.
=> Update some old label values

cli/command/formatter/logrus.go, cli/command/formatter/logrus_test.go
This change adds the missing error handling in logrus.go and adds a test
for TextFormatter.Format()
This should be enough to close #88
=> formatter: handle errors & test TextFormatter.Format()

cli/command/cluster/health.go, cli/command/node/health.go
This change adds a new function UpdateNodeHealth() in "node" package
to query and update health status of a given node.
This fixes both cluster health and node health issues (with missing data plane status).
=> [dev-1997] cluster & node: fix querying health status

cli/command/formatter/logrus_test.go
We have tests for sorted output. Disabled sorting results in
unpredictable map based output.
This issue was found while running tests for https://github.com/storageos/go-cli/pull/97 and https://github.com/storageos/go-cli/pull/98 .
=> formatter: remove disable sorting testcase

cli/command/policy/create.go, cli/command/policy/create_test.go
This change replaces jsonlParse() with jsonlValidate(), which just
validates a given jsonl byte array.
Multiple policy creation fix is done by sending multiple client requests
with a single json object at a time. go-api has a bug in marshalling
jsonl data.
=> [dev-1995] policy: add jsonlValidate() & fix multiple policy creation

cli/command/user/update.go, cli/command/user/update_test.go
This change adds a check in updateOptions.processGroups() to look for an
existing group before adding a given group.
=> [dev-2007] user: fix group duplication while updating user

cli/command/volume/create.go
Volume size 0 results in creating volume with default size. This change
adds a size check before posting to api endpoint.
=> [dev-2002] volume: show error if volume size 0 is explicitly specified

Gopkg.lock, cli/command/formatter/cluster_health.go, cli/command/formatter/node_health.go, cli/command/node/health.go, vendor/github.com/storageos/go-api/types/health.go
With this change, cli would no longer query dataplane endpoint for health
status, but use the dataplane status returned by the controlplane health
endpoint.
Depends on go-api: https://github.com/storageos/go-api/pull/41
=> health: Use the unified controlplane health endpoint

cli/command/user/update.go, cli/command/user/update_test.go
This change adds a check to look if a group is in addGroups and
removeGroups at the same time. Also adds tests for the same.
=> user: check for same group in add and remove while updating

cli/command/user/update.go, cli/command/user/update_test.go
This change removes passing `command.StorageOSCli` argument to
verifyUpdate() because it's not used in the function.
=> user: change verifyUpdate() signature and add tests

cli/command/formatter/cluster_health.go
We no longer receive DFS server status from health status.
=> DEV-2170: remove DFS server status from health

Gopkg.lock, cli/command/cli.go, cli/command/login/cmd.go, vendor/github.com/storageos/go-api/client.go, vendor/github.com/storageos/go-api/health.go, version/client.go
Setting user-agent with version is needed in order to differentiate CLI
from other clients and be able to perform version compatibility for any
breaking changes.
This would require updating the go-cli version once https://github.com/storageos/go-api/pull/44 is merged.
=> Set user-agent with version

cli/command/cluster/health.go, cli/command/formatter/cluster_health.go, cli/command/formatter/cluster_health_test.go, cli/command/formatter/custom.go, cli/command/formatter/formatter.go, cli/command/formatter/node.go, cli/command/formatter/node_test.go, cli/command/formatter/policy.go, cli/command/formatter/pool.go, cli/command/formatter/user.go, cli/command/formatter/volume.go
Changes to CLI output width and consistency. All table format headers should now be uppercase, with underscores as separators, whilst sizes should all be in the same unit.
Command specific changes:
`node ls`: Removed the revision from the version field, should be the release tag
`cluster health`: Should show only CP status and DP status by default, but when the status is degraded will show the parts which aren't healthy. `--format detailed` had been added to retain the previous output (minus the scheduler).
=> DEV-1799: CLI output width & consistency changes

Dockerfile
The pipeline relies on having the binary at /storageos
=> Revert path change in container, breaks e2e pipeline

pkg/jointools/expand.go, pkg/jointools/expand_test.go, pkg/jointools/verify.go
HTTPS should no longer be an invalid scheme. If the URI scheme was considered a valid scheme, then it would be replaced with TCP in all instances.
I'm in favour of removing the `jointools` package - it seems like the API client should be responsible for dealing with that. But, in the meantime the behaviour should be fixed.
=> Preserve URI scheme of JOIN components.

cli/command/cluster/health.go, cli/command/cluster/inspect.go, cli/command/logs/cmd.go, cli/command/logs/view.go, cli/command/node/health.go, cli/command/system/version.go, pkg/constants/constants.go
Use this as the default value for timeout options, as the
http client dial timeout is more lenient than it used to be.
This accounts for bad network paths, slow connections etc.
=> DEV-2477: Add default API call timeout

cli/command/node/cmd.go, cli/command/node/delete.go
Allows a node to be removed from the cluster if it is already offline.
=> node: add node leave support

cli/command/formatter/node.go, cli/command/formatter/node_test.go, cli/command/formatter/pool.go, cli/command/formatter/util.go, cli/command/formatter/volume.go, cli/command/formatter/volume_test.go
Fix size inconsistency by converting all size representation from decimal to binary (1 KiB = 1024).
Ref: https://en.wikipedia.org/wiki/Binary_prefix
=> DEV-2853: convert all size representation to binary (1 KiB = 1024)

Gopkg.lock, cli/command/cluster/cmd.go, cli/command/cluster/maintenance.go, vendor/github.com/storageos/go-api/cluster.go, vendor/github.com/storageos/go-api/types/cluster.go
Support `storageos cluster maintenance [enable|disable|inspect]`.
See in the ticket for the CI link.
Original PR here:
https://github.com/storageos/go-cli/pull/162
=> DEV-2865: support maintenance mode management (resubmit with CI e2e test)

Makefile
RHEL/CentOS/Fedora don't have shasum, but have separate binaries for sha1, sha256 etc.
=> Fall back to sha256sum if shasum not found

cli/command/formatter/cluster_health.go, cli/command/formatter/connectivity.go, cli/command/formatter/namespace.go, cli/command/formatter/node.go, cli/command/formatter/node_health.go, cli/command/formatter/policy.go, cli/command/formatter/pool.go, cli/command/formatter/rule.go, cli/command/formatter/user.go, cli/command/formatter/util.go, cli/command/formatter/volume.go, cli/command/system/version.go
Custom table formats were being ignored due to the behaviour of try format unless.
This has been fixed by adding a dynamic matching mechanism to supliment the current solution.
=> Fix table based formatting

types/sortable_node_type_test.go, types/types.go
Fixes panic when node list has a node name shorter then the others:
```
$ kubectl get nodes -o wide
NAME                         STATUS   ROLES    AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION            CONTAINER-RUNTIME
kind-v1.14.3-control-plane   Ready    master   19m   v1.14.3   172.17.0.4    <none>        Ubuntu 19.04   4.20.11-100.fc28.x86_64   containerd://1.2.6-0ubuntu1
kind-v1.14.3-worker          Ready    <none>   19m   v1.14.3   172.17.0.2    <none>        Ubuntu 19.04   4.20.11-100.fc28.x86_64   containerd://1.2.6-0ubuntu1
kind-v1.14.3-worker2         Ready    <none>   19m   v1.14.3   172.17.0.3    <none>        Ubuntu 19.04   4.20.11-100.fc28.x86_64   containerd://1.2.6-0ubuntu1
```
```
$ ./storageos_linux_amd64-1.2.1 node ls  
panic: runtime …
```
=> fix panic when one node name is shorter than the other
